var fs = require("fs");
var terminalText = process.argv;

var htmlTitle = "My First Webpage generated by JavaScript";

//Example of blacklist
if(terminalText[3] == undefined  || terminalText[3] == "none") {
  console.log("There was no color specificed, so the dafault white will be used.");

  terminalText[3] == "transparent"; //in css "trans-parent" means invisible/null which is white
}


//Example for whitelist
if (terminalText[3] != "red" || terminalText[3] != "green") {
  console.log("sorry that is not a [rper color value. we have defaulted you a transparent background");
  terminalText[3] == "transparent";
}


var htmlStyle = `
body {
  background-color: ${terminalText[3]};
}
`;


var htmlBody = `
<p>${terminalText[4]}</p>
`;

var htmlFileName = terminalText[2];


var html = `
<!doctype html>

<html lang="en">
<head>
<meta charset="utf-8">

<title>${htmlTitle}</title>
<meta name="description" content="The HTML5 Herald">
<meta name="author" content="SitePoint">

<link rel="stylesheet" href="css/styles.css?v=1.0">

<style>${htmlStyle}</style>
</head>

<body>
${htmlBody}
<script src="js/scripts.js"></script>
</body>
</html>
`;

if (htmlFileName == "" || htmlFileName == undefined) {
  console.log("You are missing a file name, cannot continue. ERROR: 232382938");
  return;
}

var fullFileName = htmlFileName + ".html";

//utf8 is for the file, unlike in the html template meta charset, which is for the browser.
fs.writeFileSync(fullFileName, html ,"utf8");// being used to this ("htmlFileName")

