var fs = require("fs");

var terminalText = process.argv;

var htmlTitle = "My First Webpage generated by JavaScript";

var htmlStyle = `
`;

var htmlFileName = "homework1";

var htmlBody = `
<p>${terminalText[2]}</p>
`;



var html = `
<!doctype html>

<html lang="en">
<head>
<meta charset="utf-8">

<title>${htmlTitle}</title>
<meta name="description" content="The HTML5 Herald">
<meta name="author" content="SitePoint">

<link rel="stylesheet" href="css/styles.css?v=1.0">

<style>${htmlStyle}</style>
</head>

<body>
${htmlBody}
<script src="js/scripts.js"></script>
</body>
</html>
`;


var fullFileName = htmlFileName + ".html";

//utf8 is for the file, unlike in the html template meta charset, which is for the browser.
// being used to this ("htmlFileName")
fs.writeFileSync(fullFileName, html ,"utf8");
